services:

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: pulsehouse-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  redpanda-init:
    image: redpandadata/redpanda:latest
    container_name: pulsehouse-redpanda-init
    depends_on:
      - redpanda
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until rpk cluster info -X brokers=redpanda:9092 >/dev/null 2>&1; do
          sleep 1
        done
        rpk topic create product-events \
          -X brokers=redpanda:9092 \
          --partitions 1 \
          --replicas 1 \
          --if-not-exists

  redpanda-connect:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: pulsehouse-connect

    depends_on:
      redpanda-init:
        condition: service_completed_successfully

    command:
      - run
      - /connect/product-events.yaml

    volumes:
      - ./connect:/connect

    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: pulsehouse-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d

volumes:
  redpanda-data:
  clickhouse-data:
